### ISSUE TITLE
Did you see jump in performance when using multiple 512 (long document)?

### ISSUE THREAD

**Issue by lucaguarro** [heraclex12/VLSP2020-Fake-News-Detection#1]
Hi, just curious if your model performed better when adding an LSTM layer to allow it to handle longer sequences? Trying to gauge if doing something similar for my problem would be a worthy endeavor.

**Comment by heraclex12** [comment]
In my problem, I admit that adding an LSTM layer didn't boost the performance. Moreover, I didn't spend much time conducting the experiments more intensive. You can read further on [this](https://arxiv.org/abs/1910.10781) and try more. I am also grateful if you can share your experiment results.

**Comment by lucaguarro** [comment]
1. Interesting. I am also taking a look at this [repository](https://github.com/helmy-elrais/RoBERT_Recurrence_over_BERT/blob/master/train.ipynb) that does something similar to what you are doing except they do not perform back-propagation on both the transformer model and LSTM layer at the same time. Instead they fine-tune a transformer model on the segmented dataset. They then run the same dataset through the transformer to extract segmented embeddings and only then use the segmented embeddings to train an LSTM. Intuitively, doing back-propagation separately like this seems like it would perform worse than your approach yet they report a boost in performance.

2. With regards to the paper you cited, do you know if any implementation of "ToBERT" exists? I've only been able to find implementations of RoBERT (yours and the other one I cited)

**Comment by heraclex12** [comment]
I am sure about the implementation of ToBERT exists. But I don't remember where I saw it. Sorry for being unable to help you.

**Comment by lucaguarro** [comment]
Mm okay. I'll start off with RoBERT and hopefully it will work well enough for me. Thanks
